"""add change_log table

Revision ID: f8226aa5b304
Revises: a29c5eaaecdf
Create Date: 2025-12-12 18:57:54.017500

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f8226aa5b304'
down_revision: str | Sequence[str] | None = 'a29c5eaaecdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changelog_file_path', 'change_log', ['file_path'], unique=False)
    op.create_index('idx_changelog_timestamp', 'change_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_changelog_timestamp', table_name='change_log')
    op.drop_index('idx_changelog_file_path', table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
